### ISSUE TITLE
Error: [ng:areq] Argument 'ProductListCtrl' is not a function, got undefined

### ISSUE THREAD

**Issue by kdevunoori** [DeborahK/AngularF2BWebAPI#10]
Can you please help me in resolving this issue? 
Please find the files attached for the code.
# Index.html

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Acme Product Management</title>

```
<!-- Style sheets -->
<link href="Content/bootstrap.css" rel="stylesheet" />
```

</head>

<body ng-app="productManagement"  ng-strict-di>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="navbar-brand">Acme Product Management</div>
            </div>
        </div>
    </nav>

```
<div class="container">
    <div ng-include="'app/products/productListView.html'"></div>
</div>

<!-- Library Scripts -->
<script src="scripts/angular.js"></script>
 <script src="Scripts/angular-resource.js"></script>

<!-- Application Script -->
<script src="app/app.js"></script>

<!-- Services -->
<script src="common/common.services.js"></script>
<!-- Product Controllers -->
<script src="app/products/productListCtrl.js"></script>
```

</body>
# </html>
# app.js

var app = angular.module("productManagement",
    ["common.services"]);
# 
# common.services.js

 angular
        .module("common.services",
                        ["ngResource"])
        .constant("appSettings",
        {
            serverPath: "http://localhost:52396/"
#         });
# productListCtrl.js

angular
        .module("productManagement")
        .controller("ProductListCtrl",
                    ["productResource",
                        ProductListCtrl]);

```
function ProductListCtrl(productResource) {
    var vm = this;
    productResource.query(function (data) {
        vm.products = data;
    });
}
```
# 
# productResource.js

angular
    .module("common.services")
    .factory("productResource",
            ["$resource",
             "appSettings",
                productResource])

function productResource($resource, appSettings) {
    return $resource(appSettings.serverPath + "/api/products/:id");
# }

**Comment by human3820917** [comment]
There is a typo in the original productListCtrl.js. The typo is ProductListCtrl ...

```
angular
    .module("productManagement")
    .controller("ProductListCtrl",
                 ProductListCtrl);
```

**ProductListCtrl** should be **productListCtrl**

**Comment by DeborahK** [comment]
I assume from the above that this issue was resolved. I'm closing it. Thanks!
