### ISSUE TITLE
unable to access the controller(typescript & angularjs) in jasmine 

### ISSUE THREAD

**Issue by dileepkumar19** [DeborahK/AngularF2BWebAPI#13]
**angularjs && Typescript Controller**

module app.controller {
class MainCtrl {
        static $inject = ['$scope', '$rootScope', '$interval', '$http', 'unityService',
            'adalAuthenticationService', '$location', '$window', 'analyticsService', 'homePageSetting',
            'unityCommonService', '$timeout', '$cookies', '$routeParams', '$compile', '$filter'];
        }
constructor(
            private $scope,
            private $rootScope,
            private $interval,
            private $http,
            private unityService: app.services.unityService,
            private adalAuthenticationService,
            private $location,
            private $window,
            private analyticsService,
            private homePageSetting,
            private unityCommonService,
            private $timeout,
            private $cookies,
            private $routeParams,
            private $compile,
            private $filter

        ) { }
 angular.module('UnityApp').controller('MainCtrl', MainCtrl);
}

**Jasmine Test For Controller**

beforeEach(function () { angular.module("UnityApp") });

it("should make a string more exciting", inject(function (_$controller_, _$rootScope_) {
        var controller =
            _$controller_('MainCtrl', {
                $scope: _$rootScope_.$new(),
            })

    }));

i m unable to access the scope  in MainCtrl

**Comment by DeborahK** [comment]
This issue is over a year old. I assume at this point it has been resolved or is no longer relevant. I'm closing this issue. Please reopen if necessary.
