### ISSUE TITLE
Files not present

### ISSUE THREAD

**Issue by glen-dale** [DeborahK/AngularF2BWebAPI#14]
The ProductRepository.cs and product.json files are not present in the APM.WebAPI project in the StartFiles directory.

**Comment by DeborahK** [comment]
This is an *old* AngularJS (Angular v1.x) course, so there is no product.json file.

The ProductRepository.cs file is here: https://github.com/DeborahK/AngularF2BWebAPI/tree/master/startFiles/APM.WebAPI/Models

**Comment by glen-dale** [comment]
Thanks Deborah.

Glen

**Comment by DeborahK** [comment]
Are you looking for a course on Angular that is updated and includes Web API? If so, I can provide a link.

**Comment by glen-dale** [comment]
Hi Deborah

That would be great. Thanks very much.

Regards

Glen

**Comment by DeborahK** [comment]
This is a great course by Shawn that covers how to build an Angular application and use it with asp.net core.

https://app.pluralsight.com/library/courses/aspnetcore-mvc-efcore-bootstrap-angular-web

**Comment by glen-dale** [comment]
Hi Deborah

This looks perfect for me, thanks for your help

Regards

Glen
