### ISSUE TITLE
External social logins

### ISSUE THREAD

**Issue by SkyQuant** [DeborahK/AngularF2BWebAPI#2]
Dear Deborah!
Thanks for your interesting cources :-) 

In this repository could be nice also to see External Login implementation as here http://bitoftech.net/2014/08/11/asp-net-web-api-2-external-logins-social-logins-facebook-google-angularjs-app/ but with internal ASP.NET posibilities, like

```
            app.UseTwitterAuthentication(
                consumerKey: "",
                consumerSecret: "");
```

**Comment by SkyQuant** [comment]
Could be helpful http://stackoverflow.com/questions/21065648/asp-net-web-api-2-how-to-login-with-external-authentication-services

**Comment by DeborahK** [comment]
Thank you for your suggestion and posting a link for some sample code.
It would be an interesting project to fork this repository and add alternate solutions for the authentication.

**Comment by SkyQuant** [comment]
Deborah, it's idea for your next course - how to make mobile Apache Cordova app in AngularJS +  Material Design or Ionic with social logins ;-)

**Comment by joshhurley** [comment]
I've try creating the app twice now and keep getting stuck tying to call the WebAPI. It isn't a CORS error. Instead I'm receiving the following error:
![image](https://cloud.githubusercontent.com/assets/4236598/9969260/6f5c85e4-5e1b-11e5-8c96-94fe91d64769.png) 

Error: [ng:areq] Argument 'ProductListCtrl' is not a function, got undefined

Angular points to this link for details about the error:
https://docs.angularjs.org/error/$injector/unpr?p0=productResourceProvider 

Looking at Chrome Network, it doesn't look like it is even calling WebAPI:
![image](https://cloud.githubusercontent.com/assets/4236598/9969350/05c3ebee-5e1c-11e5-8bd5-da998e12c0d4.png)

Could you point me in the right direction to resolve? Thanks.

Josh.
