### ISSUE TITLE
Argument 'ProductListCtrl' is not a function, got undefined

### ISSUE THREAD

**Issue by ghost** [DeborahK/AngularF2BWebAPI#6]
I've tried creating the app twice now and keep getting stuck tying to call the WebAPI. It isn't a CORS error. Instead I'm receiving the following error:
![image](https://cloud.githubusercontent.com/assets/4236598/9969260/6f5c85e4-5e1b-11e5-8c96-94fe91d64769.png) 

Error: [ng:areq] Argument 'ProductListCtrl' is not a function, got undefined

Angular points to this link for details about the error:
https://docs.angularjs.org/error/$injector/unpr?p0=productResourceProvider 

Looking at Chrome Network, it doesn't look like it is even calling WebAPI:
![image](https://cloud.githubusercontent.com/assets/4236598/9969350/05c3ebee-5e1c-11e5-8bd5-da998e12c0d4.png)

Could you point me in the right direction to resolve? Thanks.

Josh.

**Comment by DeborahK** [comment]
This is almost always one of the following:
- The Script tag is missing from the index.html file.
- The reference to the module is missing (or misspelled) from the app.js file
- The reference to the dependency is missing (or misspelled) from the controller

NOTE: Casing is critical. If the code defines myService, the dependency must say "myService" not "MyService".

Hope this helps!

**Comment by ghost** [comment]
I must be missing it

**Index.html**

``` html
    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Acme Product Management</title>

        <!-- Style sheets -->
        <link href="Content/bootstrap.css" rel="stylesheet" />
    </head>

    <body ng-app="productManagement">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-brand">Acme Product Management</div>
                </div>
            </div>
        </nav>

        <div class="container">
            <div ng-include="'app/products/productListView.html'"></div>
        </div>

        <!-- Library Scripts -->
        <script src="scripts/angular.js"></script>
        <script src="Scripts/angular-resource.js"></script>

        <!-- Application Script -->
        <script src="app/app.js"></script>

        <!-- Services -->
        <script src="common/common.services.js"></script>
        <script src="common/productResource.js"></script>

        <!-- Product Controllers -->
        <script src="app/products/productListCtrl.js"></script>
    </body>
    </html>
```

**app.js:**

``` javascript
    (function () {
        "use strict";

        var app = angular.module("productManagement", ["common.services"]);
    }());
```

**productListCtrl.js**

``` javascript
    (function () {
        "use strict";
        angular
            .module("productManagement")
            .controller("productListCtrl", ["productResource", ProductListCtrl]);

        function ProductListCtrl(productResource) {
            var vm = this;

            productResource.query(function (data) {
                vm.products = data;
            });
        }
    }());
```

**productResource.js**

``` javascript
(function () {
    "use strict";

    angular
        .module("common.services")
        .factory("productResource", ["$resource", "appSettings", productResource])

    function productResource($resource, appSettings) {
        return $resource(appSettings.serverPath + "/api/products/:id");
    }
});
```

**Comment by DeborahK** [comment]
.controller("productListCtrl", ["productResource", ProductListCtrl]);
.................. ^ This needs to be a capital "P"

**Comment by ghost** [comment]
That solved it, thank you for the quick response. I'm missing my compiled languages right now! 

Best,

Josh.

**Comment by DeborahK** [comment]
Glad that solved it!

**Comment by usman10scorpio** [comment]
@DeborahK thanks for the case sensitive tip :)
