### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by tonymedrano** [DeborahK/AngularF2BWebAPI#7]
Errors:
- Failed to load resource: the server responded with a status of 404 (Not Found)
- Failed to load resource: the server responded with a status of 401 (Unauthorized)

Everything was fine until start with currentUser.js

(function () {
    "use strict";

```
angular
    .module("common.services")
    .factory("currentUser", currentUser)

function currentUser() {
    var profile = {
        isLoggedIn: false,
        username: "",
        token: ""
    };

    var setProfile = function (username, token) {
        profile.username = username;
        profile.token = token;
        profile.isLoggedIn = true;
    };

    var getProfile = function () {
        return profile;
    }

    return {
        setProfile: setProfile,
        getProfile: getProfile
    }
}
```

})();

maiCtrl.js:

(function () {
    "use strict";

```
angular
.module("productManagement")
.controller("MainCtrl",
            ["userAccount",
             "currentUser",
               MainCtrl]);

function MainCtrl(userAccount, currentUser) {
    var vm = this;
    vm.isLoggedIn = function () {
        return currentUser.getProfile().isLoggedIn;
    };
    vm.userData = {
        userName: '',
        email: '',
        password: '',
        confirmPassword: ''
    };

    vm.registerUser = function () {
        vm.userData.confirmPassword = vm.userData.password;

        userAccount.registration.registerUser(vm.userData, function (data) {
            vm.confirmPassword = "";
            vm.message = "...Registration successful";
            vm.login();
        },
        function (response) {
            vm.isLoggedIn = false;
            vm.message = response.statusText + "\r\n";
            if (response.data.exceptionMessage) {
                vm.message += response.data.exceptionMessage;
            }

            if (response.data.modelState) {
                for (var key in response.data.modelState) {
                    vm.message += response.data.modelState[key] + "\r\n";
                }
            }
        });
    };

    vm.login = function () {
        vm.userData.grant_type = "password";
        vm.userData.userName = vm.userData.email;

        userAccount.login.loginUser(vm.userData,
            function (data) {
                vm.message = "";
                vm.password = "";
                currentUser.setProfile(vm.userData.userName, data.access_token);
            },
        function (response) {
            vm.password = "";
            vm.message = response.statusText + "\r\n";
            if (response.data.exceptionMessage) {
                vm.message += response.data.exceptionMessage;
            }

            if (response.data.error) {
                vm.message += response.data.error;
            }
        });
    };
}
```

})();

Thanks.

**Comment by tonymedrano** [comment]
Hope you can help me, thanks!

**Comment by DeborahK** [comment]
I'm out off the office and won't be able to look at this until I return. 
Have you seen this? http://blogs.msmvps.com/deborahk/angular-front-to-back-with-web-api-problem-solver/

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by tonymedrano** [comment]
![screen shot 2015-11-04 at 2 00 51 pm](https://cloud.githubusercontent.com/assets/6433516/10948623/80b11124-82fc-11e5-88a7-363365fae645.png)

**Comment by tonymedrano** [comment]
Hi Deborah, I have it and work but whenI  start "User Authorization" get the error above the screen shot.

**Comment by tonymedrano** [comment]
Hi Deborah, thanks but the problem came up with currentUser.js and when I updated productResource.js:



(function () {
    "use strict";

    angular
        .module("common.services")
        .factory("productResource",
                ["$resource", "appSettings", "currentUser", productResource])

    function productResource($resource, appSettings, currentUser) {
        return $resource(appSettings.serverPath + "/api/product/:id", null,
            {
                'get': {
                    headers: {'Authorization': 'Bearer' + currentUser.getProfile().token}
                },

                'save': {
                    headers: { 'Authorization': 'Bearer' + currentUser.getProfile().token }
                },

                'update': {
                    method: 'PUT',
                    headers: { 'Authorization': 'Bearer' + currentUser.getProfile().token }
                }
           });
    }
}());

**Comment by tonymedrano** [comment]
Hi Deborah, do you have an example with a nested json to see how it works?. Thanks

**Comment by tonymedrano** [comment]
And thank you for the course, it was great!

**Comment by DeborahK** [comment]
I assume this issue has been resolved or is no longer relevant. I'm closing this issue. Thanks!
